.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH hashline-hash 1  "hash " 
.SH NAME
hash \- Output line hashes for a file
.SH SYNOPSIS
\fBhash\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIFILE\fR> 
.SH DESCRIPTION
Output line hashes for a file
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIFILE\fR>
File path to hash
