.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH hashline-apply 1  "apply " 
.SH NAME
apply \- Apply hashline edits from stdin JSON to a file
.SH SYNOPSIS
\fBapply\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Apply hashline edits from stdin JSON to a file
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
